apiVersion: v1
kind: Service
metadata:
  name: k8s-hello-python-svc
spec:
  type: NodePort
  selector:
    app: k8s-hello-python
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-hello-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-hello-python
  template:
    metadata:
      labels:
        app: k8s-hello-python
    spec:
      containers:
      - name: k8s-hello-python
        image: smiggiddy/python-hello-k8
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 5000
